### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by ytaylor** [Adalab/modulo-1-evaluacion-intermedia-aliciaapadron#1]
Muy buen trabajo @aliciaapadron!!!

Aquí tienes unos consejos para mejorar tu ejercicio:

- [x] HTML > HEADER: La etiqueta `img` debe tener el atributo `title`: https://github.com/Adalab/modulo-1-evaluacion-intermedia-aliciaapadron/blob/b6f131923824697903c8d901eb4f1c2735243311/index.html#L16-L17 
- [x] HTML > HEADER: Necesitamos al menos una etiqueta `ul`, encapsula los enlaces en un listado: https://github.com/Adalab/modulo-1-evaluacion-intermedia-aliciaapadron/blob/b6f131923824697903c8d901eb4f1c2735243311/index.html#L19-L24 
- [x] HTML > HEADER: Los textos de los enlaces deben ser "Blog" y "Contacto" . Debemos ponerlo en mayúsculas con CSS. Y no es necesario que lo englobes dentro de la etiqueta `p`: https://github.com/Adalab/modulo-1-evaluacion-intermedia-aliciaapadron/blob/b6f131923824697903c8d901eb4f1c2735243311/index.html#L19-L21
- [x] HTML > HEADER: Los enlaces tienen que tener el atributo `title`.
- [x] HTML > MAIN: Necesitamos al menos una etiqueta `h1`, pon el texto dentro de la etiqueta `h1`: https://github.com/Adalab/modulo-1-evaluacion-intermedia-aliciaapadron/blob/b6f131923824697903c8d901eb4f1c2735243311/index.html#L28-L30 
- [x] HTML > MAIN: El contenido exacto del h1 debe ser "Creando diversidad digital". Debemos poner las primeras letras en mayúsculas con CSS.
- [x] CSS > ESTILOS REPETIDOS: Hay estilos repetidos en las media queries que no son necesarios, es mejor quitarlos. `.header { display: flex }`
- [x] CSS > FONT-FAMILY: Es recomendable que la fuente del body sea Rubik para aprovechar la herencia.
- [x] CSS > FONT-FAMILY: La fuente del h1 debe ser Rubik
- [x] CSS > FONT-SIZE: El tamaño del h1 en móvil debe ser 30px.
- [x] CSS > FONT-SIZE: El tamaño del h1 en tablet debe ser 40px.
- [x] CSS > PADDING: El padding de los enlaces no debería ser 0. Auméntalo para aumentar el área clickable, pero manteniendo los requisitos del diseño.
- [x] Utiliza correctamente las etiquetas semánticas, estas etiquetas `body` no engloban nada : https://github.com/Adalab/modulo-1-evaluacion-intermedia-aliciaapadron/blob/b6f131923824697903c8d901eb4f1c2735243311/index.html#L33-L35
- [x] Elimina el fichero .gitgnore o utilizalo correctamente.

Es posible que cuando corrijas uno de estos puntos, otros se corrijan solos, ya que unos dependen de otros.

Y recuerda algo muy importante:

- Escribe tu código en inglés.
- Escribe todos los ficheros y carpetas en inglés.
- Los commits también tienen que ser en inglés, empezando por un verbo en infinitivo.

Ánimo y si tienes cualquier duda avísame!!!

> Con cada mejora que hagas, márcala como completada en este issue y su súbela a este repo.

> Este issue ha sido creado automáticamente por ello puede tener algún error, si hay algo que no te encaja escribe por slack a tu tutora.

> Para corregir el ejercicio buscamos determinadas palabras en el código para identificar las secciones. Por ejemplo buscamos **Creando** para buscar el título de la página. Si has escrito mal alguna palabra en el código es posible que te aparezcan aquí falsos errores.

> Por favor no cierres este issue, ya lo haremos nosotros.

**Comment by ytaylordev** [comment]
Good job!
